/* This file will be used to store all the Response Messages of API */

// CODES BLOCK
// - SUCCESS BLOCK - 200
CODE_RESPONSE_SUCCESS = 200

// - 300

// - SERVER ERROR BLOCK - 400
CODE_RESPONSE_ERROR = 400

// - 500

// - 600

// - 700

// - 800

// - 900


// MESSAGES BLOCK
// - SUCCESS BLOCK
MESSAGE_RESPONSE_SUCCESS = "Successful Response"
MESSAGE_RESPONSE_ERROR = "Error Response"


module.exports = {
    // CODE BLOCK
    CODE_RESPONSE_ERROR:CODE_RESPONSE_ERROR,
    CODE_RESPONSE_SUCCESS: CODE_RESPONSE_SUCCESS,

    // MESSAGE BLOCK
    MESSAGE_RESPONSE_SUCCESS: MESSAGE_RESPONSE_SUCCESS,
    MESSAGE_RESPONSE_ERROR:MESSAGE_RESPONSE_ERROR
}
